const heatshrink = require("heatshrink")

function decompress(string) {
    return heatshrink.decompress(atob(string))
}

exports = {
    '0': decompress('ktAwMB/4GBg//8AEBh/8CAUf4AECvgDCgIRCgEOEYcwBoYyJh///AEBv//E4MD//+F4X/+AEB///wBCCHwU/I4RPBKAQk/En4kmAA4qBAAMEBAdwAYUHBoc+AYUDF4Q+BEwRHBIQI5BA'),
    '1': decompress('ktAwMB/4AB8EHAgUAn4DB/AND4EPAYP+gF/AgPwgYNCwEfAYP8gAk/En4k/En4kC'),
    '2': decompress('ktAwMBAwUH/AECh/AAgUeCodwAYUBwAEChgNDkANDGJE/////EBAYP/4EPAYP+gF/AgPwgYNCwEfAYP8gAIC8EHAgQkqDoJ4GvADCgZzDnAIDCIccO4fgSY0D+B7DM3AkWAA53DggIDmD5HhwNDSYh4Dj6GD'),
    '3': decompress('ktAwMBAwUH/AECh/AAgUeCodwAYUBwAEChgNDkANDGJE/////EBAYP/4EPAYP+gF/AgPwgYNCwEfAYP8gAIC8EHAgQkpV1xu/EhpgSoADCgwIDmADCgeAAgU8AYUH8B7DA=='),
    '4': decompress('ktAwMBgE///ggEB///BoMP//4AgN///AgED//+BAMf//wAgIWBwEAg///gIBEn4kXABcCAgcYAgY4BAAMHBAc8AYUBEwcPIQRRCJIJRBJIRRBJIQIC8BRBJIRRBJIJRCNwJRBNwQk/Ei4A=='),
    '5': decompress('ktAwMB/4HCg/gAgU8AYUB4AEChgaDsADCgQIDiAyNh////+gF/AgPwgYDB/+Aj4DB/kABAXgg4ECgE/AYP4J4IAB4AkpPYXwAgUfwAECnxfD/ADCgaFDj4NDviTDCQcPEoZ2/EhrXNAAlAAYUGBAcwQoaTDnihD8B7DA'),
    '6': decompress('ktAwMB/4HCg/gAgU8AYUB4AEChgaDsADCgQIDiAyNh////+gF/AgPwgYDB/+Aj4DB/kABAXgg4ECgE/AYP4J4IAB4AkpPYXwAgUfwCAGgCJDgYIDjAEDoB8NJIIsCKIQ0BKIRJCFgJJCSYf4AgJuBXYJuBKIQkpAA58DggIDuCPDBoc+QoYvCHwImCI4KUCv4A=='),
    '7': decompress('ktAwMBAwUH/AECh/AAgUeCodwAYUBwAEChgNDkANDGJE/////EBAYP/4EPAYP+gF/AgPwgYNCwEfAYP8gAIC8EHAgQk/En4k/Eio'),
    '8': decompress('ktAwMB/4GBg//8AEBh/8CAUf4AECvgDCgIRCgEOEYcwBoYyJh///AEBv//E4MD//+F4X/+AEB///wBCCHwU/I4RPBKAQkpAFpu/EhwAHFQIABggIDuADCg4NDnwDCgaeDn4mCI4JCBHIIA=='),
    '9': decompress('ktAwMB/4GBg//8AEBh/8CAUf4AECvgDCgIRCgEOEYcwBoYyJh///AEBv//E4MD//+F4X/+AEB///wBCCHwU/I4RPBKAQkpABcCAgcYAgaFDg4IDnh8DEwcPIQRRCJIJRBJIRRBJIQIC8BRBJIRRBJIJRCNwJRBNwQkoPhoAEoADCgz0HgawBQAsHWAJ7CA=='),

    ':': decompress('iFAwMB/4AO/Ef8EH4EDwEBAIIpLB4YVBDIIdBF54//A='),

    'am': decompress('jFAwMB//D/4CDwICHgACFv/+AQn8gE//kYAQf4nkfAQvwv0PAQcAh/ggEHAQkD4P/wYCCHQOBwf/4ICCg//8ACFh//+ACCJYIADBYoXFgf/4ACFPYOAAQpwBRYICCvwCGhE8iACDjEQhkYmACCh0AuACFh8AIgICFwICE4YCDA=='),
    'pm': decompress('jFAwMB//D/4CDwICHgACFv/+AQn8gE//kYAQf4nkfAQvwv0PAQcAh/ggEHAQkD4P/wYCCHQOBwf/4ICCg//8ACFh//+ACCJYIADBYoXFgf/4ACFPYOAAQpwBRYICCvwCGhE8iACDjEQhkYmACCh0AuACFh8AIgICFwICE4YCDA==')
}